### ISSUE TITLE
django 3.2 compatible?

### ISSUE THREAD

**Issue by auvipy** [Nepherhotep/django-orm-sugar#2]
i want to know if this package still work with latest LTS of django?

**Comment by auvipy** [comment]
CI should be moved to travis-ci.com or github action

**Comment by cybergrind** [comment]
> CI should be moved to travis-ci.com or github action

Yep.

> i want to know if this package still work with latest LTS of django?

I don't see any broken test on the latest django version, so it looks working.
We're also internally using it on django 3.1 or 3.2 so it is working

**Comment by auvipy** [comment]
thats cool!
